# Generated by Django 6.0.5 on 2026-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_periode', models.CharField(max_length=20)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('nama_periode', models.CharField(max_length=100)),
                ('tanggal_awal_kuliah', models.DateField()),
                ('tanggal_akhir_kuliah', models.DateField()),
                ('tanggal_awal_uts', models.DateField()),
                ('tanggal_awal_uas', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
