# Generated by Django 6.0.5 on 2026-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodeakademik',
            name='jumlah_pertemuan_kuliah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodeakademik',
            name='ketua_ujian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodeakademik',
            name='kuesioner_layanan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodeakademik',
            name='minimal_presensi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodeakademik',
            name='nama_singkat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodeakademik',
            name='tanggal_akhir_uas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodeakademik',
            name='tanggal_akhir_uts',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodeakademik',
            name='tanggal_awal_uas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodeakademik',
            name='tanggal_awal_uts',
            field=models.DateField(blank=True, null=True),
        ),
    ]
