# Generated by Django 6.0.5 on 2026-05-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_periodeakademik_jumlah_pertemuan_kuliah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodeakademik',
            name='kode_periode',
            field=models.CharField(max_length=5),
        ),
    ]
